#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S3,     usSensor,       sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// main program
task main()
{
	//get battery level
	float batteryLevel = getBatteryVoltage();
	//starts a timer when program starts to check idle time since turned on
	clearTimer(T1);
	//Sets the sound volume of the EV3 speaker to 80
	setSoundVolume(100);

  //loops infinitely
	while (true) {
		if (getTouchValue(touchSensor) == 1 ||getUSDistance(usSensor) <= 25 )
		{
			if (time1[T1] < 30000 ){
				//plays active sound file if the timer is less than 30 seconds
				playSoundFile("Hello");
				//restarts the timer and starts one to count idle time since last sense
				clearTimer(T1);
				//after it does the action pauses program for 5 seconds
				delay(5000);
			}else if (time1[T1] > 33000){ //plays a idle then active sound file if idle timer is more than 33 seconds, accomodates for idle notification which occurs at 30-31 sec with 2 second delay

				playSoundFile("Bravo");
				clearTimer(T1);
				delay(5000);
			}
	 //if no distance or touch detection
	 }else{
	    //if timer is between 30-31 seconds (1.1 second for idle notification so that if a battery notification played and the time was 30 seconds, the battery would play then pause 1 sec then loop back)
	    //although delay on active sounds when sensed are 5 seconds if they are activated it would no longer be considered idle therefore not 5 seconds given for idle notification
			if (time1[T1] >= 30000 && time1[T1] <= 31000){
				playSoundFile("Snoring");
				//2.1 second delay after playing file to prevent a repeat of idle notification which would be annoying  e.g. if played at 45 sec it would delay to 47.1 sec which is not in the requirement for playing idle notification
        delay(2000);
      //if idle timer is more or equal than 50 seconds and less than or equal to 52 seconds... (2 sec time frame to accomodate automatic battery notification which has 1 sec delay)
			}else if (time1[T1] >= 50000 && time1[T1] <= 52000){
			playSoundFile("Goodbye");
			delay(15000);
		}else{
		//battery switch statements to play different sounds at different levels
		switch (batteryLevel) {
			case 1:
				playSoundFile("Overpower");
				delay(1000);
				break;
			case 0.75:
				playSoundFile("Good");
				delay(1000);
				break;
			case 0.50:
				playSoundFile("Okay");
				delay(1000);
				break;
			case 0.25:
				playSoundFile("Uh oh");
				delay(1000);
				break;
			case 0.1:
				playSoundFile("Crying");
				delay(1000);
				break;
			default:
				break;
			}
		}

}
}
}
